// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 문서 링크가 가리키는 곳의 성격. 나무위키는 셋을 다르게 꾸민다.
 */
export type DocumentLinkKind = "existing" | "missing" | "current";
