// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StyleDeclaration } from "./StyleDeclaration";

/**
 * 통과시키는 속성. 자리마다 값이 하나씩이므로 같은 속성을 두 번 쓴 입력은
 * 먼저 쓴 값만 남는다 — 브라우저가 하는 것과 같다.
 *
 * `id`는 문서 앵커(`s-1`, `fn-1`)와 충돌할 수 있어 받지 않는다 — 이 구조체에 자리가
 * 없다는 것이 곧 그 보장이다. 이미지의 `src`도 나무마크 이미지 문법이 대신하므로
 * [`HtmlAttributes::source`]는 `<video>`에만 붙는다.
 *
 * `href`는 연다 — 나무위키가 그렇게 하고(렌더확정: `틀:문서 가져옴/나무위키`의
 * `{{{#!html <a href="https://namu.wiki/w/…">…</a>}}}`가 실제로 링크로 나온다),
 * 웹 주소만 통과하므로 여기 담긴 값은 이미 `http`·`https`·`ftp`다.
 *
 * `target`·`rel`은 없다. 위키 입력이 정할 것이 아니라 렌더러의 표현 정책이다.
 */
export type HtmlAttributes = { class: string | null, href: string | null, style: Array<StyleDeclaration>, source: string | null, 
/**
 * `<video>`의 표시 속성. CSS 길이가 아니라 HTML 속성이라 표기를 그대로 둔다.
 */
width: string | null, height: string | null, controls: boolean, };
