// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 통과시키는 태그. 텍스트 서식과 문단 구조에 더해 `<video>`까지다(렌더확정: `틀:video`의
 * `{{{#!html <video src="…" …></video>}}}`가 the seed에서 실제 `<video>`로 나온다).
 * 스크립트·삽입·폼은 없다.
 */
export type HtmlTag = "anchor" | "bold" | "italic" | "underline" | "strikethrough" | "strong" | "emphasis" | "subscript" | "superscript" | "lineBreak" | "span" | "division" | "code" | "small" | "big" | "wordBreakOpportunity" | "video";
