// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HtmlAttributes } from "./HtmlAttributes";
import type { HtmlTag } from "./HtmlTag";

/**
 * 걸러 낸 `#!html`의 노드 하나.
 */
export type HtmlNode = { "type": "text", text: string, } | { "type": "element", tag: HtmlTag, attributes: HtmlAttributes, children: Array<HtmlNode>, };
