// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAlignment } from "./ImageAlignment";
import type { ImageTheme } from "./ImageTheme";

export type ImageLayout = { width: string | null, height: string | null, align: ImageAlignment | null, backgroundColor: string | null, theme: ImageTheme | null, };
