// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderTableCell } from "./RenderTableCell";

export type RenderTableRow = { cells: Array<RenderTableCell>, };
