// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalAlignment } from "./HorizontalAlignment";
import type { RenderBlock } from "./RenderBlock";
import type { RenderTableAttribute } from "./RenderTableAttribute";
import type { VerticalAlignment } from "./VerticalAlignment";

export type RenderTableCell = { 
/**
 * 지정하지 않았으면 None (기본 1, `colspan`·`rowspan` 미방출).
 */
columnSpan: number | null, rowSpan: number | null, 
/**
 * 지정하지 않았으면 None (기본 왼쪽, `text-align` 미방출).
 */
horizontalAlignment: HorizontalAlignment | null, verticalAlignment: VerticalAlignment | null, attributes: Array<RenderTableAttribute>, blocks: Array<RenderBlock>, };
