// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { DocumentLinkKind } from "./DocumentLinkKind";
import type { HtmlNode } from "./HtmlNode";
import type { ImageLayout } from "./ImageLayout";
import type { RenderBlock } from "./RenderBlock";
import type { StyleDeclaration } from "./StyleDeclaration";
import type { TextStyle } from "./TextStyle";
import type { VideoProvider } from "./VideoProvider";

export type RenderInline = { "type": "text", text: string, } | { "type": "lineBreak" } | { "type": "styled", style: TextStyle, content: Array<RenderInline>, } | { "type": "literal", text: string, } | { "type": "colored", color: Color, content: Array<RenderInline>, } | { "type": "sized", level: number, content: Array<RenderInline>, } | { "type": "documentLink", title: string, anchor: string | null, kind: DocumentLinkKind, 
/**
 * 화면에 나오는 글자. 표시부를 안 적었으면 resolve가 적힌 대상으로 채운다.
 */
display: Array<RenderInline>, } | { "type": "externalLink", url: string, display: Array<RenderInline> | null, } | { "type": "image", fileName: string, url: string | null, layout: ImageLayout, } | { "type": "footnoteReference", 
/**
 * 화면 표기 이름 (무명 각주는 참조 번호 "16", 이름 각주는 그 이름)
 */
label: string, 
/**
 * 문서 안 모든 각주 참조에 차례로 붙는 번호. 재참조도 제 번호를 받는다.
 * 무명 각주의 라벨이 곧 이 번호다(렌더확정: `[A]`가 13·14를 쓰면 다음
 * 무명 각주는 13이 아니라 16이다).
 */
number: number, 
/**
 * 각주 내용의 글자만 뽑은 것. 나무위키는 이걸 `title`에 실어 툴팁으로 보여준다.
 */
tooltip: string, } | { "type": "video", provider: VideoProvider, identifier: string, width: string | null, height: string | null, } | { "type": "ruby", content: string, ruby: string, 
/**
 * `color=`로 준 루비 글자색. 나무위키는 `<rt>` 안을 span으로 감싼다.
 */
color: string | null, } | { "type": "math", formula: string, } | { "type": "anchor", name: string, } | { "type": "clearFix" } | { "type": "tableOfContents" } | { "type": "footnoteSection", notes: Array<number>, } | { "type": "blocks", blocks: Array<RenderBlock>, } | { "type": "wikiStyle", style: Array<StyleDeclaration>, darkStyle: Array<StyleDeclaration>, blocks: Array<RenderBlock>, } | { "type": "folding", 
/**
 * 접기 문구. 위키 문법이 적용되지 않아 글자 그대로다.
 */
summary: string, blocks: Array<RenderBlock>, } | { "type": "codeBlock", language: string | null, source: string, } | { "type": "html", nodes: Array<HtmlNode>, } | { "type": "unresolved", name: string, argument: string | null, };
