// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListKind } from "./ListKind";
import type { RenderInline } from "./RenderInline";
import type { RenderListItem } from "./RenderListItem";
import type { RenderTable } from "./RenderTable";

export type RenderBlock = { "type": "heading", level: number, folded: boolean, 
/**
 * layout pass가 채우는 계층 번호 ("1.2"). 앵커는 `s-{number}`.
 */
number: string, 
/**
 * 문단명 앵커. `[[#개요]]`로 걸 수 있도록 제목 글자를 그대로 쓴다.
 */
anchor: string, content: Array<RenderInline>, } | { "type": "paragraph", content: Array<RenderInline>, } | { "type": "horizontalRule" } | { "type": "quote", blocks: Array<RenderBlock>, } | { "type": "list", kind: ListKind, items: Array<RenderListItem>, } | { "type": "indent", blocks: Array<RenderBlock>, } | { "type": "table", table: RenderTable, };
