// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderBlock } from "./RenderBlock";
import type { RenderedFootnote } from "./RenderedFootnote";
import type { TableOfContentsEntry } from "./TableOfContentsEntry";

/**
 * layout까지 끝난 최종 렌더링 입력.
 *
 * 문서 전역 정보(목차·각주)는 트리 밖 최상위 목록이 소유하고 트리 안에는 자리표시만
 * 남는다. 그래야 layout이 헤딩을 다 본 뒤 목차를 채우려고 트리를 다시 훑지 않아도 되고,
 * 여러 번 참조된 각주의 내용이 참조 수만큼 실려 나가지도 않는다. 대신 `[목차]`·`[각주]`를
 * 그리는 쪽은 노드만으로는 부족하고 이 목록을 함께 봐야 한다.
 */
export type RenderTree = { redirect: string | null, blocks: Array<RenderBlock>, categories: Array<string>, 
/**
 * 문서 전체 목차. `[목차]` 자리마다 이 목록을 그대로 그린다.
 */
tableOfContents: Array<TableOfContentsEntry>, 
/**
 * 문서의 모든 각주를 방출 순서대로 담는다. 각주 내용의 유일한 소유자이며,
 * [`RenderInline::FootnoteSection`]은 이 목록의 인덱스만 가리킨다.
 */
footnotes: Array<RenderedFootnote>, };
