// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderInline } from "./RenderInline";
import type { RenderTableRow } from "./RenderTableRow";

export type RenderTable = { caption: Array<RenderInline> | null, rows: Array<RenderTableRow>, };
