// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableAttributeScope } from "./TableAttributeScope";
import type { TableStyleProperty } from "./TableStyleProperty";

/**
 * 표 스타일 속성. 색·크기 표기 해석과 방출 여부 판정을 resolve가 끝냈으므로,
 * 백엔드는 문자열 이름 대조나 값 파싱 없이 확정된 값을 방출만 한다.
 */
export type RenderTableAttribute = { scope: TableAttributeScope, property: TableStyleProperty, };
