// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderBlock } from "./RenderBlock";

export type RenderListItem = { startNumber: number | null, blocks: Array<RenderBlock>, };
