// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderInline } from "./RenderInline";

export type RenderedFootnote = { 
/**
 * 화면 표기 이름. 무명 각주는 참조 번호("16"), 이름 각주는 그 이름("A").
 */
label: string, 
/**
 * 본문에서 이 각주를 참조한 자리들의 번호. 역링크가 여기로 되돌아간다.
 */
referenceNumbers: Array<number>, content: Array<RenderInline>, };
