// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `#!wiki`가 실어 온 CSS를 나무위키가 받아들이는 만큼만 걸러 낸 뒤 남은 선언 하나.
 *
 * 위키 입력이 CSS로 나가는 통로라 색·크기와 같은 값 해석 부류다 — 나무위키는 여기를
 * 그냥 흘려보내지 않고 무효·미지원 선언을 버린다([`StyleDeclaration::parse`] 참고).
 */
export type StyleDeclaration = { property: string, value: string, };
