// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalAlignment } from "./HorizontalAlignment";

/**
 * 값이 이미 파싱된 표 스타일 속성.
 *
 * 색은 듀얼 표기(`#fff,#000`)의 라이트 값만 담는다 — 표 색의 다크 모드는 후속 과제다.
 * 색 표기가 아닌 값이 들어온 선언은 resolve가 통째로 버리므로 여기 나타나지 않는다.
 */
export type TableStyleProperty = { "type": "backgroundColor", color: string, } | { "type": "color", color: string, } | { "type": "borderColor", color: string, } | { "type": "width", width: string, } | { "type": "height", height: string, } | { "type": "textAlign", alignment: HorizontalAlignment, } | { "type": "align", alignment: HorizontalAlignment, } | { "type": "noPadding" };
