// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableAttributeScope = { "type": "cell" } | { "type": "column", columns: number, } | { "type": "row" } | { "type": "table" };
