// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderInline } from "./RenderInline";

export type TableOfContentsEntry = { 
/**
 * "1.2.3" — 앵커는 `s-{number}`
 */
number: string, depth: number, 
/**
 * 헤딩 제목 그대로. 링크도 살아 있다(렌더확정: `== [[/TeX|수식]] ==`의 목차 항목이
 * the seed에서도 `<a href='/w/…/TeX'>수식</a>`이다).
 */
title: Array<RenderInline>, };
